./main -astar -f 8puzzle_instances.txt > "8puzzle_astar.txt"
./main -bfs -f 8puzzle_instances.txt > "8puzzle_bfs.txt"
./main -idastar -f 8puzzle_instances.txt > "8puzzle_idastar.txt"
./main -idfs -f 8puzzle_instances.txt > "8puzzle_idfs.txt"
./main -gbfs -f 8puzzle_instances.txt > "8puzzle_gbfs.txt"